{% set name = "libsmu" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/analogdevicesinc/{{ name }}/archive/master.tar.gz
  sha256: 8299b8e1cf66eaa84a67f9046bb236809308dec31355d0faf9fd58b3c561546b

build:
  number: 2
  run_exports:
    - {{ pin_subpackage('libsmu', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('libudev-devel') }}  # [linux]
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - pkg-config  # [not win]
  host:
    - pip
    - boost-cpp
    - _openmp_mutex  # [linux]
    - libusb >=1
    - python
    - setuptools
    - cython
  run:
    - python

test:
  commands:
    # verify that executables can be run
    - smu -h

    # verify that headers get installed
    - test -f $PREFIX/include/libsmu/libsmu.hpp  # [not win]
    - if not exist %PREFIX%\\Library\\include\\libsmu\\libsmu.hpp exit 1  # [win]

    # verify that libraries get installed
    - test -f $PREFIX/lib/libsmu${SHLIB_EXT}  # [not win]
    - if not exist %PREFIX%\\Library\\bin\\libsmu.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\libsmu.lib exit 1  # [win]
  imports:
    - pysmu

about:
  home: https://github.com/analogdevicesinc/libsmu
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Software abstractions for the analog signal exploration tools'
  description: |
    libsmu contains abstractions for streaming data to and from USB-connected
    analog interface devices, currently supporting the Analog Devices' ADALM1000.
    Building off of LibUSB for cross-platform operation, it offers the sourcing
    of repeated waveforms, configuration of hardware, and measuring of signals.
  doc_url: https://analogdevicesinc.github.io/libsmu/
  dev_url: https://github.com/analogdevicesinc/libsmu

extra:
  recipe-maintainers:
    - tfcollins
